create database customer_shopping_behavior_kaggle;
use customer_shopping_behavior_kaggle;

describe customerdata;
show tables;

create table customerdata (
    customerid int,
    age int,
    gender varchar(10),
    itempurchased varchar(100),
    category varchar(50),
    purchaseamount decimal(10,2),
    location varchar(50),
    size varchar(20),
    color varchar(30),
    season varchar(20),
    reviewrating decimal(3,2),
    subscriptionstatus varchar(20),
    shippingtype varchar(20),
    discountapplied varchar(5),
    promocodeused varchar(5),
    previouspurchases int,
    paymentmethod varchar(30),
    frequencyofpurchases varchar(30)
);

select count(*) from customerdata;

-- Q1. Total revenue generated by male vs. female customers
select 
    gender,
    sum(purchaseamount) as revenue
from customerdata
group by gender;

-- Q2. Customers who used a discount and spent more than the average purchase amount
select 
    customerid,
    purchaseamount as purchase_amount
from customerdata
where discountapplied = 'Yes'
  and purchaseamount > (
        select avg (purchaseamount)
        from customerdata
  );
  
-- Q3. Top 5 products with the highest average review rating
select 
    itempurchased,
    round(avg(reviewrating), 2) as average_product_rating
from customerdata
group by itempurchased
order by avg(reviewrating) desc
limit 5;

-- Q4. Average purchase amount by shipping type (Standard vs Express)
select
	shippingtype,
    round(avg(purchaseamount), 2) as avg_purchase_amount
from customerdata
where shippingtype in ("Standard", "Express")
group by shippingtype;

-- Q5. Compare spending between subscribers and non-subscribers
select 
    subscriptionstatus,
    count(customerid) as total_customers,
    round(avg(purchaseamount), 2) as avg_spend,
    round(sum(purchaseamount), 2) as total_revenue
from customerdata
group by subscriptionstatus
order by total_revenue desc;

-- Q6. Top 5 products with the highest discount usage percentage
select 
    itempurchased,
    round(
        100.0 * sum(case when discountapplied = 'Yes' then 1 else 0 end) / count(*),
        2
    ) as discount_rate
from customerdata
group by itempurchased
order by discount_rate desc
limit 5;

-- Q7. Customer segmentation based on previous purchases
select 
    customersegment,
    count(*) as number_of_customers
from (
    select 
        customerid,
        case 
            when previouspurchases = 1 then 'New'
            when previouspurchases between 2 and 10 then 'Returning'
            else 'Loyal'
        end as customersegment
    from customerdata
) as segments
group by customersegment;

-- Q8. Top 3 most purchased products in each category
select 
    category,
    itempurchased,
    totalorders
from (
    select 
        category,
        itempurchased,
        count(customeriD) as totalorders,
        row_number() over (
            partition by category 
            order by count(customerid) desc
        ) as rn
    from customerdata
    group by category, itempurchased
) ranked
where rn <= 3
order by category, totalorders desc;

-- Q9. Subscription status of repeat buyers (more than 5 purchases)
select 
    subscriptionstatus,
    count(customeriD) as repeat_buyers
from customerdata
where previouspurchases > 5
group by subscriptionstatus;

-- Q10. Revenue contribution by age group
select 
    age,
    sum(purchaseamount) as total_revenue
from customerdata
group by age
order by total_revenue desc;